# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Corne Nice Nano v2 OLED Colemak-DH'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
